### ISSUE TITLE
Perhaps rename this repository with something more descriptive?

### ISSUE THREAD

**Issue by paulhendricks** [CCS-Lab/cocaine-dependence#2]

**Comment by paulhendricks** [comment]
Perhaps we can rename it to `cocaine-dependence` and have this relate to code and data for http://journal.frontiersin.org/article/10.3389/fpsyt.2016.00034/full.

**Comment by paulhendricks** [comment]
@youngahn Thoughts?

**Comment by youngahn** [comment]
I can’t think of better name yet. Personally I think easyML is intuitive to me but am open to other names.

**Comment by paulhendricks** [comment]
The name can always be changed later. I've changed this to cocaine-dependency in case anyone comes looking for the code and data supporting the published paper. I've also renamed the R and Python directories so as to be a bit cleaner and move the code to the top most level directory.
